import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="border-b">
          <nav className="mx-auto max-w-5xl px-6 py-4 flex items-center justify-between">
            <div className="font-bold text-lg">AI Study Planner</div>
            <div className="flex gap-4 text-sm">
              <a className="hover:underline" href="/setup">Setup</a>
              <a className="hover:underline" href="/availability">Availability</a>
              <a className="hover:underline" href="/plan">Plan</a>
            </div>
          </nav>
        </header>

        <main className="mx-auto max-w-5xl px-6 py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
